ESX = exports["es_extended"]:getSharedObject()
RegisterNetEvent('weed:1')
AddEventHandler('weed:1', function()
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('marijuana', 10)
    Wait(2000)
    xPlayer.addAccountMoney('money', 3000)
end)

RegisterNetEvent('weed:2')
AddEventHandler('weed:2', function()
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('marijuana', 10)
    Wait(2000)
    xPlayer.addAccountMoney('money', 3000)
end)

RegisterNetEvent('weed:3')
AddEventHandler('weed:3', function()
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('marijuana', 10)
    Wait(2000)
    xPlayer.addAccountMoney('money', 3000)
end)

RegisterNetEvent('weed:4')
AddEventHandler('weed:4', function()
    local xPlayer = ESX.GetPlayerFromId(source)
    xPlayer.removeInventoryItem('marijuana', 10)
    Wait(2000)
    xPlayer.addAccountMoney('money', 3000)
end)